import { LLModels } from "../model-types";

export const GroqModels: LLModels[] = [
  {
    id: "gemma-7b-it",
    name: "Gemma 7B IT",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "gemma2-9b-it",
    name: "Gemma 2 9B IT",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.1-70b-versatile",
    name: "Llama 3.1 70B Versatile",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text", "tool"],
  },
  {
    id: "llama-3.1-8b-instant",
    name: "Llama 3.1 8B Instant",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.2-11b-text-preview",
    name: "Llama 3.2 11B Text Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.2-11b-vision-preview",
    name: "Llama 3.2 11B Vision Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.2-1b-preview",
    name: "Llama 3.2 1B Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.2-3b-preview",
    name: "Llama 3.2 3B Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama-3.2-90b-text-preview",
    name: "Llama 3.2 90B Text Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text", "tool"],
  },
  {
    id: "llama-3.2-90b-vision-preview",
    name: "Llama 3.2 90B Vision Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text", "tool", "images"],
  },
  {
    id: "llama-guard-3-8b",
    name: "Llama Guard 3 8B",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama3-70b-8192",
    name: "Llama 3 70B 8192",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama3-8b-8192",
    name: "Llama 3 8B 8192",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "llama3-groq-70b-8192-tool-use-preview",
    name: "Llama 3 Groq 70B 8192 Tool Use Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text", "tool"],
  },
  {
    id: "llama3-groq-8b-8192-tool-use-preview",
    name: "Llama 3 Groq 8B 8192 Tool Use Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text", "tool"],
  },
  {
    id: "llava-v1.5-7b-4096-preview",
    name: "Llava V1.5 7B 4096 Preview",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
  {
    id: "mixtral-8x7b-32768",
    name: "Mixtral 8x7B 32768",
    provider: "Groq",
    providerId: "groq",
    status: "online",
    capability: ["text"],
  },
] as const;
